### ISSUE TITLE
Post rating in the grid?

### ISSUE THREAD

**Issue by fw1002** [bootscore/bs-grid#5]
I am using another plugin (wpDiscuz) to collect ratings and comments of posts.
I am thinking of also showing the average rating in the bs-grid content.
Do you think it is achievable by adding extra code to the template?

**Comment by crftwrk** [comment]
Of course, you can show everything you want in the loop. Just need the snippet for the stars. 

As they wrote here https://wpdiscuz.com/community/troubleshooting/display-post-rating-and-number-of-ratings-in-the-loop/ and here https://wpdiscuz.com/community/f-a-q/wpdiscuz-shortcode-2/, there are shortcodes `[wpdrating]` for them.

So, it's not tested because I don't use this plugin but this one should to the trick:

`<?php echo do_shortcode("[wpdrating]"); ?>`

Paste it for example after the closing `</h2>` tag in template file. If this not works, please open a topic in the WPDiscuz forum to get the correct shortcode.

Does this help?

**Comment by fw1002** [comment]
Hi Basti,

Thank you very much for the reply and the kind support.
It does work.
I am very new to the Bootstrap and php. I don't know much about coding.
I try to self-learn from the documentation.
Your support really made my day.
If you are interested, my website URL is https://reviewfromuser.com
I am trying to build a website for user reviews.

Best regards,

Frank

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------
在 2022年4月19日 星期二 下午 10:40，Basti ***@***.***> 寫道：

**Comment by crftwrk** [comment]
You‘re welcome 👍
